package handler

import (
	"crypto/hmac"
	"crypto/sha1"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"quickdesk/signaling/internal/config"
	"quickdesk/signaling/internal/models"
	"quickdesk/signaling/internal/service"
	"runtime"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/shirou/gopsutil/v3/cpu"
	"github.com/shirou/gopsutil/v3/disk"
	"github.com/shirou/gopsutil/v3/host"
	"github.com/shirou/gopsutil/v3/mem"
	psnet "github.com/shirou/gopsutil/v3/net"
)

type APIHandler struct {
	deviceService *service.DeviceService
	authService   *service.AuthService
	presetService *service.PresetService
	config        *config.Config
	wsHandler     *WSHandler
	// network IO stats for computing real-time speed
	lastNetIO     psnet.IOCountersStat
	lastNetIOTime time.Time
	uploadSpeed   float64 // KB/s
	downloadSpeed float64 // KB/s
}

func NewAPIHandler(deviceService *service.DeviceService, authService *service.AuthService, presetService *service.PresetService, cfg *config.Config) *APIHandler {
	return &APIHandler{
		deviceService: deviceService,
		authService:   authService,
		presetService: presetService,
		config:        cfg,
		lastNetIOTime: time.Now(),
	}
}

// SetWSHandler sets the WebSocket handler reference (called after WSHandler is created)
func (h *APIHandler) SetWSHandler(ws *WSHandler) {
	h.wsHandler = ws
}

// GetFeatures handles GET /api/v1/features
// Returns feature flags so clients can adapt their UI (e.g. hide SMS login when not configured).
func (h *APIHandler) GetFeatures(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"sms_enabled": h.config.Sms.Enabled,
	})
}

// RegisterDevice handles POST /api/v1/devices/register
// Request: { "device_id": "optional", "os": "Windows", "os_version": "11", "app_version": "1.0.0" }
// Response: { "device_id": "123456789", "is_new": true/false }
func (h *APIHandler) RegisterDevice(c *gin.Context) {
	var req service.RegisterDeviceRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
		return
	}
	
	device, isNew, err := h.deviceService.RegisterDevice(c.Request.Context(), &req)
	if err != nil {
		log.Printf("Failed to register device: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to register device"})
		return
	}
	
	// Note: Temporary password is now generated by Host and sent via WebSocket
	// No longer generated here during registration
	
	c.JSON(http.StatusOK, gin.H{
		"device_id": device.DeviceID,
		"is_new":    isNew,
	})
	
	if isNew {
		log.Printf("New device registered: device_id=%s", device.DeviceID)
	} else {
		log.Printf("Existing device verified: device_id=%s", device.DeviceID)
	}
}

// GetDevice handles GET /api/v1/devices/:device_id
func (h *APIHandler) GetDevice(c *gin.Context) {
	deviceID := c.Param("device_id")
	
	device, err := h.deviceService.GetByDeviceID(c.Request.Context(), deviceID)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "device not found"})
		return
	}
	
	c.JSON(http.StatusOK, device)
}

// VerifyPassword handles POST /api/v1/auth/verify
// Request: { "device_id": "123456789", "password": "654321" }
// Response: { "valid": true, "connection_token": "..." } or { "valid": false, "error": "HOST_OFFLINE" }
func (h *APIHandler) VerifyPassword(c *gin.Context) {
	var req struct {
		DeviceID string `json:"device_id" binding:"required"`
		Password string `json:"password" binding:"required"`
	}
	
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
		return
	}
	
	// Check if host is online (has WebSocket connection)
	if h.wsHandler == nil || !h.wsHandler.IsHostOnline(req.DeviceID) {
		log.Printf("Auth verify failed: device %s is offline", req.DeviceID)
		c.JSON(http.StatusOK, gin.H{
			"valid":   false,
			"error":   "HOST_OFFLINE",
			"message": "设备不在线",
		})
		return
	}
	
	// Verify password
	if !h.authService.VerifyDevice(c.Request.Context(), req.DeviceID, req.Password) {
		log.Printf("Auth verify failed: invalid password for device %s", req.DeviceID)
		c.JSON(http.StatusOK, gin.H{
			"valid":   false,
			"error":   "INVALID_PASSWORD",
			"message": "密码错误",
		})
		return
	}
	
	// Generate connection token (simple implementation for now)
	token := generateRandomHex(16)
	
	log.Printf("Auth verify success: device %s", req.DeviceID)
	c.JSON(http.StatusOK, gin.H{
		"valid":            true,
		"connection_token": token,
	})
}

// GetDeviceStatus handles GET /api/v1/devices/:device_id/status
func (h *APIHandler) GetDeviceStatus(c *gin.Context) {
	deviceID := c.Param("device_id")
	
	// Check if host is online
	online := h.wsHandler != nil && h.wsHandler.IsHostOnline(deviceID)
	
	c.JSON(http.StatusOK, gin.H{
		"device_id": deviceID,
		"online":    online,
	})
}

// GetIceConfig handles GET /api/v1/ice-config
// Returns ICE server configuration with time-limited TURN credentials (coturn REST API style).
func (h *APIHandler) GetIceConfig(c *gin.Context) {
	ice := h.config.Ice
	ttl := ice.CredentialTTL
	if ttl <= 0 {
		ttl = 86400
	}

	iceServers := []gin.H{}

	if len(ice.TurnURLs) > 0 && ice.AuthSecret != "" {
		expiry := time.Now().Unix() + int64(ttl)
		username := fmt.Sprintf("%d:%s", expiry, generateRandomHex(4))

		mac := hmac.New(sha1.New, []byte(ice.AuthSecret))
		mac.Write([]byte(username))
		credential := base64.StdEncoding.EncodeToString(mac.Sum(nil))

		turnEntry := gin.H{
			"urls":       ice.TurnURLs,
			"username":   username,
			"credential": credential,
		}
		if ice.MaxRateKbps > 0 {
			turnEntry["maxRateKbps"] = ice.MaxRateKbps
		}
		iceServers = append(iceServers, turnEntry)
	}

	if len(ice.StunURLs) > 0 {
		iceServers = append(iceServers, gin.H{
			"urls": ice.StunURLs,
		})
	}

	c.JSON(http.StatusOK, gin.H{
		"iceServers":       iceServers,
		"lifetimeDuration": fmt.Sprintf("%d.000s", ttl),
	})
}

// GetPreset handles GET /api/v1/preset
// Returns preset configuration as a flat JSON for clients.
func (h *APIHandler) GetPreset(c *gin.Context) {
	preset, err := h.presetService.GetPreset()
	if err != nil {
		log.Printf("Failed to get preset: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to get preset"})
		return
	}

	// Build response: parse stored JSON strings into proper JSON objects
	response := gin.H{
		"min_version": preset.MinVersion,
	}

	// Parse notice JSON
	if preset.Notice != "" {
		var notice interface{}
		if json.Unmarshal([]byte(preset.Notice), &notice) == nil {
			response["notice"] = notice
		} else {
			response["notice"] = gin.H{}
		}
	} else {
		response["notice"] = gin.H{}
	}

	// Parse links JSON
	if preset.Links != "" {
		var links interface{}
		if json.Unmarshal([]byte(preset.Links), &links) == nil {
			response["links"] = links
		} else {
			response["links"] = gin.H{}
		}
	} else {
		response["links"] = gin.H{}
	}

	c.JSON(http.StatusOK, response)
}

// GetAdminPreset handles GET /api/v1/admin/preset
// Returns raw preset record for admin management.
func (h *APIHandler) GetAdminPreset(c *gin.Context) {
	preset, err := h.presetService.GetPreset()
	if err != nil {
		log.Printf("Failed to get preset: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to get preset"})
		return
	}
	c.JSON(http.StatusOK, preset)
}

// UpdateAdminPreset handles PUT /api/v1/admin/preset
// Request body: { "notice": "{...}", "links": "{...}", "min_version": "1.0.0" }
func (h *APIHandler) UpdateAdminPreset(c *gin.Context) {
	var req models.Preset
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
		return
	}

	if err := h.presetService.UpsertPreset(&req); err != nil {
		log.Printf("Failed to update preset: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to update preset"})
		return
	}

	log.Printf("Preset updated: min_version=%s", req.MinVersion)
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

// Health check endpoint
func (h *APIHandler) HealthCheck(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"status":  "ok",
		"service": "quickdesk-signaling",
	})
}

// GetAdminDevices handles GET /admin/devices
func (h *APIHandler) GetAdminDevices(c *gin.Context) {
	ctx := c.Request.Context()

	devices, err := h.deviceService.GetAllDevices(ctx)
	if err != nil {
		log.Printf("Failed to get devices: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to get devices"})
		return
	}

	var result []gin.H
	for _, device := range devices {
		online := h.wsHandler != nil && h.wsHandler.IsHostOnline(device.DeviceID)
		result = append(result, gin.H{
			"id":          device.ID,
			"device_id":   device.DeviceID,
			"device_uuid": device.DeviceUUID,
			"os":          device.OS,
			"os_version":  device.OSVersion,
			"app_version": device.AppVersion,
			"online":      online,
			"last_seen":   device.LastSeen,
			"created_at":  device.CreatedAt,
			"updated_at":  device.UpdatedAt,
		})
	}

	c.JSON(http.StatusOK, gin.H{"devices": result})
}

// GetAdminStats handles GET /admin/stats
func (h *APIHandler) GetAdminStats(c *gin.Context) {
	ctx := c.Request.Context()

	devices, err := h.deviceService.GetAllDevices(ctx)
	if err != nil {
		log.Printf("Failed to get devices: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to get devices"})
		return
	}

	totalDevices := len(devices)
	onlineDevices := 0
	offlineDevices := 0

	for _, device := range devices {
		if h.wsHandler != nil && h.wsHandler.IsHostOnline(device.DeviceID) {
			onlineDevices++
		} else {
			offlineDevices++
		}
	}

	onlineRate := 0
	if totalDevices > 0 {
		onlineRate = (onlineDevices * 100) / totalDevices
	}

	c.JSON(http.StatusOK, gin.H{
		"totalDevices":   totalDevices,
		"onlineDevices":  onlineDevices,
		"offlineDevices": offlineDevices,
		"onlineRate":     onlineRate,
	})
}

// GetSystemStatus handles GET /admin/system/status
// Returns CPU, memory, disk usage and network IO stats via gopsutil.
func (h *APIHandler) GetSystemStatus(c *gin.Context) {
	cpuPercent, err := cpu.Percent(0, false)
	cpuUsage := "0%"
	if err == nil && len(cpuPercent) > 0 {
		cpuUsage = fmt.Sprintf("%.1f%%", cpuPercent[0])
	}

	memInfo, err := mem.VirtualMemory()
	memUsage := "0%"
	if err == nil && memInfo != nil {
		memUsage = fmt.Sprintf("%.1f%%", memInfo.UsedPercent)
	}

	diskInfo, err := disk.Usage("/")
	diskUsage := "0%"
	if err == nil && diskInfo != nil {
		diskUsage = fmt.Sprintf("%.1f%%", diskInfo.UsedPercent)
	}

	hostInfo, err := host.Info()
	uptime := "00:00:00"
	if err == nil && hostInfo != nil {
		uptimeDuration := time.Duration(hostInfo.Uptime) * time.Second
		hours := int(uptimeDuration.Hours())
		minutes := int(uptimeDuration.Minutes()) % 60
		seconds := int(uptimeDuration.Seconds()) % 60
		uptime = fmt.Sprintf("%02d:%02d:%02d", hours, minutes, seconds)
	}

	var uploadTotal int64
	var downloadTotal int64

	netIO, err := psnet.IOCounters(false)
	if err == nil && len(netIO) > 0 {
		uploadTotal = int64(netIO[0].BytesSent)
		downloadTotal = int64(netIO[0].BytesRecv)

		now := time.Now()
		timeDelta := now.Sub(h.lastNetIOTime).Seconds()

		if timeDelta > 0 && h.lastNetIO.BytesSent > 0 && h.lastNetIO.BytesRecv > 0 {
			h.uploadSpeed = float64(netIO[0].BytesSent-h.lastNetIO.BytesSent) / timeDelta / 1024
			h.downloadSpeed = float64(netIO[0].BytesRecv-h.lastNetIO.BytesRecv) / timeDelta / 1024

			if h.uploadSpeed < 0 {
				h.uploadSpeed = 0
			}
			if h.downloadSpeed < 0 {
				h.downloadSpeed = 0
			}
		}

		h.lastNetIO = netIO[0]
		h.lastNetIOTime = now
	}

	c.JSON(http.StatusOK, gin.H{
		"status":        "online",
		"statusText":    "运行中",
		"cpu":           cpuUsage,
		"memory":        memUsage,
		"disk":          diskUsage,
		"apiVersion":    "v1",
		"dbStatus":      "connected",
		"dbStatusText":  "已连接",
		"network":       "ok",
		"systemVersion": runtime.Version(),
		"uptime":        uptime,
		"ip":            "0.0.0.0",
		"uploadSpeed":   h.uploadSpeed,
		"downloadSpeed": h.downloadSpeed,
		"uploadTotal":   uploadTotal,
		"downloadTotal": downloadTotal,
	})
}

// GetConnectionStatus handles GET /admin/connections
func (h *APIHandler) GetConnectionStatus(c *gin.Context) {
	var wsConnections int
	if h.wsHandler != nil {
		wsConnections = h.wsHandler.GetConnectionCount()
	}

	c.JSON(http.StatusOK, gin.H{
		"currentConnections":   wsConnections,
		"todayConnections":     wsConnections,
		"webSocketConnections": wsConnections,
		"apiRequests":          0,
	})
}

// GetActivity handles GET /admin/activity
func (h *APIHandler) GetActivity(c *gin.Context) {
	c.JSON(http.StatusOK, []gin.H{})
}
