package handler

import (
	"crypto/hmac"
	"crypto/sha1"
	"encoding/base64"
	"fmt"
	"log"
	"encoding/json"
	"net/http"
	"quickdesk/signaling/internal/config"
	"quickdesk/signaling/internal/models"
	"quickdesk/signaling/internal/service"
	"time"

	"github.com/gin-gonic/gin"
)

type APIHandler struct {
	deviceService *service.DeviceService
	authService   *service.AuthService
	presetService *service.PresetService
	config        *config.Config
	wsHandler     *WSHandler
}

func NewAPIHandler(deviceService *service.DeviceService, authService *service.AuthService, presetService *service.PresetService, cfg *config.Config) *APIHandler {
	return &APIHandler{
		deviceService: deviceService,
		authService:   authService,
		presetService: presetService,
		config:        cfg,
	}
}

// SetWSHandler sets the WebSocket handler reference (called after WSHandler is created)
func (h *APIHandler) SetWSHandler(ws *WSHandler) {
	h.wsHandler = ws
}

// RegisterDevice handles POST /api/v1/devices/register
// Request: { "device_id": "optional", "os": "Windows", "os_version": "11", "app_version": "1.0.0" }
// Response: { "device_id": "123456789", "is_new": true/false }
func (h *APIHandler) RegisterDevice(c *gin.Context) {
	var req service.RegisterDeviceRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
		return
	}
	
	device, isNew, err := h.deviceService.RegisterDevice(c.Request.Context(), &req)
	if err != nil {
		log.Printf("Failed to register device: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to register device"})
		return
	}
	
	// Note: Temporary password is now generated by Host and sent via WebSocket
	// No longer generated here during registration
	
	c.JSON(http.StatusOK, gin.H{
		"device_id": device.DeviceID,
		"is_new":    isNew,
	})
	
	if isNew {
		log.Printf("New device registered: device_id=%s", device.DeviceID)
	} else {
		log.Printf("Existing device verified: device_id=%s", device.DeviceID)
	}
}

// GetDevice handles GET /api/v1/devices/:device_id
func (h *APIHandler) GetDevice(c *gin.Context) {
	deviceID := c.Param("device_id")
	
	device, err := h.deviceService.GetByDeviceID(c.Request.Context(), deviceID)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "device not found"})
		return
	}
	
	c.JSON(http.StatusOK, device)
}

// VerifyPassword handles POST /api/v1/auth/verify
// Request: { "device_id": "123456789", "password": "654321" }
// Response: { "valid": true, "connection_token": "..." } or { "valid": false, "error": "HOST_OFFLINE" }
func (h *APIHandler) VerifyPassword(c *gin.Context) {
	var req struct {
		DeviceID string `json:"device_id" binding:"required"`
		Password string `json:"password" binding:"required"`
	}
	
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
		return
	}
	
	// Check if host is online (has WebSocket connection)
	if h.wsHandler == nil || !h.wsHandler.IsHostOnline(req.DeviceID) {
		log.Printf("Auth verify failed: device %s is offline", req.DeviceID)
		c.JSON(http.StatusOK, gin.H{
			"valid":   false,
			"error":   "HOST_OFFLINE",
			"message": "设备不在线",
		})
		return
	}
	
	// Verify password
	if !h.authService.VerifyDevice(c.Request.Context(), req.DeviceID, req.Password) {
		log.Printf("Auth verify failed: invalid password for device %s", req.DeviceID)
		c.JSON(http.StatusOK, gin.H{
			"valid":   false,
			"error":   "INVALID_PASSWORD",
			"message": "密码错误",
		})
		return
	}
	
	// Generate connection token (simple implementation for now)
	token := generateRandomHex(16)
	
	log.Printf("Auth verify success: device %s", req.DeviceID)
	c.JSON(http.StatusOK, gin.H{
		"valid":            true,
		"connection_token": token,
	})
}

// GetDeviceStatus handles GET /api/v1/devices/:device_id/status
func (h *APIHandler) GetDeviceStatus(c *gin.Context) {
	deviceID := c.Param("device_id")
	
	// Check if host is online
	online := h.wsHandler != nil && h.wsHandler.IsHostOnline(deviceID)
	
	c.JSON(http.StatusOK, gin.H{
		"device_id": deviceID,
		"online":    online,
	})
}

// GetIceConfig handles GET /api/v1/ice-config
// Returns ICE server configuration with time-limited TURN credentials (coturn REST API style).
func (h *APIHandler) GetIceConfig(c *gin.Context) {
	ice := h.config.Ice
	ttl := ice.CredentialTTL
	if ttl <= 0 {
		ttl = 86400
	}

	iceServers := []gin.H{}

	if len(ice.TurnURLs) > 0 && ice.AuthSecret != "" {
		expiry := time.Now().Unix() + int64(ttl)
		username := fmt.Sprintf("%d:%s", expiry, generateRandomHex(4))

		mac := hmac.New(sha1.New, []byte(ice.AuthSecret))
		mac.Write([]byte(username))
		credential := base64.StdEncoding.EncodeToString(mac.Sum(nil))

		turnEntry := gin.H{
			"urls":       ice.TurnURLs,
			"username":   username,
			"credential": credential,
		}
		if ice.MaxRateKbps > 0 {
			turnEntry["maxRateKbps"] = ice.MaxRateKbps
		}
		iceServers = append(iceServers, turnEntry)
	}

	if len(ice.StunURLs) > 0 {
		iceServers = append(iceServers, gin.H{
			"urls": ice.StunURLs,
		})
	}

	c.JSON(http.StatusOK, gin.H{
		"iceServers":       iceServers,
		"lifetimeDuration": fmt.Sprintf("%d.000s", ttl),
	})
}

// GetPreset handles GET /api/v1/preset
// Returns preset configuration as a flat JSON for clients.
func (h *APIHandler) GetPreset(c *gin.Context) {
	preset, err := h.presetService.GetPreset()
	if err != nil {
		log.Printf("Failed to get preset: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to get preset"})
		return
	}

	// Build response: parse stored JSON strings into proper JSON objects
	response := gin.H{
		"min_version": preset.MinVersion,
	}

	// Parse notice JSON
	if preset.Notice != "" {
		var notice interface{}
		if json.Unmarshal([]byte(preset.Notice), &notice) == nil {
			response["notice"] = notice
		} else {
			response["notice"] = gin.H{}
		}
	} else {
		response["notice"] = gin.H{}
	}

	// Parse links JSON
	if preset.Links != "" {
		var links interface{}
		if json.Unmarshal([]byte(preset.Links), &links) == nil {
			response["links"] = links
		} else {
			response["links"] = gin.H{}
		}
	} else {
		response["links"] = gin.H{}
	}

	c.JSON(http.StatusOK, response)
}

// GetAdminPreset handles GET /api/v1/admin/preset
// Returns raw preset record for admin management.
func (h *APIHandler) GetAdminPreset(c *gin.Context) {
	preset, err := h.presetService.GetPreset()
	if err != nil {
		log.Printf("Failed to get preset: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to get preset"})
		return
	}
	c.JSON(http.StatusOK, preset)
}

// UpdateAdminPreset handles PUT /api/v1/admin/preset
// Request body: { "notice": "{...}", "links": "{...}", "min_version": "1.0.0" }
func (h *APIHandler) UpdateAdminPreset(c *gin.Context) {
	var req models.Preset
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
		return
	}

	if err := h.presetService.UpsertPreset(&req); err != nil {
		log.Printf("Failed to update preset: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to update preset"})
		return
	}

	log.Printf("Preset updated: min_version=%s", req.MinVersion)
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

// Health check endpoint
func (h *APIHandler) HealthCheck(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"status":  "ok",
		"service": "quickdesk-signaling",
	})
}
