// Copyright 2026 QuickDesk Authors
// Host process communication manager

#ifndef QUICKDESK_MANAGER_HOSTMANAGER_H
#define QUICKDESK_MANAGER_HOSTMANAGER_H

#include <QObject>
#include <QJsonObject>
#include <QList>
#include <QMap>
#include <QStringList>

namespace quickdesk {

class NativeMessaging;

/**
 * @brief Session information for connected clients
 */
struct SessionInfo {
    QString connectionId;
    QString username;
    QString ip;
    QString deviceName;
    QString connectedAt;
    QString state;
};

/**
 * @brief Manages communication with the Host process
 */
class HostManager : public QObject {
    Q_OBJECT
    Q_PROPERTY(QString deviceId READ deviceId NOTIFY deviceIdChanged)
    Q_PROPERTY(QString accessCode READ accessCode NOTIFY accessCodeChanged)
    Q_PROPERTY(bool isConnected READ isConnected NOTIFY connectionStatusChanged)
    Q_PROPERTY(int clientCount READ clientCount NOTIFY clientCountChanged)
    Q_PROPERTY(QStringList clientIds READ clientIds NOTIFY clientListChanged)
    Q_PROPERTY(QString signalingState READ signalingState NOTIFY signalingStateChanged)
    Q_PROPERTY(int signalingRetryCount READ signalingRetryCount NOTIFY signalingStateChanged)
    Q_PROPERTY(int signalingNextRetryIn READ signalingNextRetryIn NOTIFY signalingStateChanged)
    Q_PROPERTY(QString signalingError READ signalingError NOTIFY signalingStateChanged)

public:
    explicit HostManager(QObject* parent = nullptr);
    ~HostManager() override = default;

    // Set the Native Messaging handler
    void setMessaging(NativeMessaging* messaging);

    // Host operations
    // Only serverUrl is needed - deviceId and accessCode are auto-generated by Host
    Q_INVOKABLE void connectToServer(const QString& serverUrl, const QString& savedAccessCode);
    Q_INVOKABLE void disconnectFromServer();
    Q_INVOKABLE void sendHello();

    // Client management
    Q_INVOKABLE void authorizeClient(const QString& connectionId, bool authorized);
    Q_INVOKABLE void kickClient(const QString& connectionId);
    
    // Access code management
    Q_INVOKABLE void refreshAccessCode();

    // State getters
    QString deviceId() const;
    QString accessCode() const;
    bool isConnected() const;
    int clientCount() const;
    QStringList clientIds() const;
    QList<SessionInfo> connectedClients() const;
    
    // Get client info for display
    Q_INVOKABLE QString getClientUsername(const QString& clientId) const;
    Q_INVOKABLE QString getClientState(const QString& clientId) const;
    
    // Signaling state getters
    QString signalingState() const;
    int signalingRetryCount() const;
    int signalingNextRetryIn() const;
    QString signalingError() const;

signals:
    void deviceIdChanged();
    void accessCodeChanged();
    void connectionStatusChanged();
    void clientCountChanged();
    void signalingStateChanged();
    
    void helloResponseReceived(const QString& version);
    void hostReady(const QString& deviceId, const QString& accessCode);
    void clientConnected(const QString& connectionId, const QJsonObject& clientInfo);
    void clientDisconnected(const QString& connectionId, const QString& reason);
    void authorizationRequested(const QString& connectionId, 
                                const QString& username, 
                                const QString& ip);
    void clientListChanged();
    void errorOccurred(const QString& code, const QString& message);
    void refreshAccessCodeResult(bool success, const QString& errorCode, const QString& errorMessage);

private slots:
    void onMessageReceived(const QJsonObject& message);
    void onMessagingError(const QString& error);

private:
    NativeMessaging* m_messaging = nullptr;
    QString m_deviceId;
    QString m_accessCode;
    bool m_isConnected = false;
    QMap<QString, SessionInfo> m_clients;
    
    // Signaling state
    QString m_signalingState = "disconnected";
    int m_signalingRetryCount = 0;
    int m_signalingNextRetryIn = 0;
    QString m_signalingError;

    void handleHelloResponse(const QJsonObject& message);
    void handleConnectResponse(const QJsonObject& message);
    void handleNatPolicyChanged(const QJsonObject& message);
    void handleHostReady(const QJsonObject& message);
    void handleAccessCodeChanged(const QJsonObject& message);
    void handleClientConnected(const QJsonObject& message);
    void handleClientDisconnected(const QJsonObject& message);
    void handleAuthorizationRequest(const QJsonObject& message);
    void handleClientListChanged(const QJsonObject& message);
    void handleError(const QJsonObject& message);
    void handleSignalingStateChanged(const QJsonObject& message);
    void handleRefreshAccessCodeResponse(const QJsonObject& message);
    void handleDisconnectResponse(const QJsonObject& message);
};

} // namespace quickdesk

#endif // QUICKDESK_MANAGER_HOSTMANAGER_H
